# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               JPEG-AI MMSP Challenge
tagline:             'Learning-based image compression'
description:         'A reserved <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that places the utmost gravity on content with a hidden drawer. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:                 http://jpegai.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Joao Ascenso
  url:               https://jpeg.org
  email:             joao.ascenso@lx.it.pt

# Custom vars
version:             1.0.0
