# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               JPEG-AI MMSP Challenge
tagline:             'Learning-based image compression'
description:         'Place to put the logo.'
url:                 http://jpegai.github.io
baseurl:             ''
paginate:            1

# About/contact
author:
  name:              Joao Ascenso
  url:               https://jpeg.org
  email:             joao.ascenso@lx.it.pt

# Custom vars
version:             1.0.0
